### ISSUE TITLE
NixOS module(s) for running a `cardano-node` SPO

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/spo-anywhere#12]
We need NixOS module(s) for starting a node as SPO (two node may be needed). We should re-use the upstream NixOS module as much as possible.

Both configuration files (we can choose to target a single public testnet for now) and secret keys can be put inside a directory in this flake for now (well, at least until we don't have to delegate real ADAs, I would avoid to push secret keys that could be used for retrieving ADAs, even for public testnets). 

For now let's keep everything in this repo, in future we may consider if to move to `cardano.nix`.

**Comment by brainrake** [comment]
fixed by https://github.com/mlabs-haskell/spo-anywhere/pull/21
