### ISSUE TITLE
NixOS test(s) for the SPO node

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/spo-anywhere#14]
Probably to be done together with #12.

It's also related to this [cardano.nix's issue](https://github.com/mlabs-haskell/cardano.nix/issues/29) and same considerations apply.

**Comment by zmrocze** [comment]
Ill try to finish this in one go with #12

**Comment by brainrake** [comment]
fixed by https://github.com/mlabs-haskell/spo-anywhere/pull/21
