### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/spo-anywhere#23]
This issue aggregates all the issues needed to be addressed for the Milestone 3.
- [x] #26
- [x] #27
- [x] #24 
- [x] #25 

For now I would say to consider deployment where everything is on the same machine.
Depending on our situation when we'll reach deliverables we can consider multi machines deployments.

**Comment by nrutledge** [comment]
Previous PoA example for reference: https://milestones.projectcatalyst.io/projects/1000125/milestones/2

**Comment by zmrocze** [comment]
submitted, accepted
