### ISSUE TITLE
Imperatively run an SPO on a public testnet

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/spo-anywhere#27]
It would be nice having a step by step guide of what needs to be done to run an SPO on a public testnet, especially in terms of all the needed files and the exact commands to run.

This can be done also on non NixOS machines using docker.

This way, when the [other milestone 3 issues](#23) will be implemented, we will be able to simply re-use these files in our `nixos-anywhere` script.

**Comment by nrutledge** [comment]
All steps are now documented in https://github.com/mlabs-haskell/apex-prime-spo-setup
