### ISSUE TITLE
Bug: can't copy keys at installation

### ISSUE THREAD

**Issue by zmrocze** [mlabs-haskell/spo-anywhere#39]
The installation script copies node keys over. Care needs to be taken about key permissions. In post installation configuration (using `no-reboot` nixos-anywhere option) the keys ownership is assigned to the node.

The bug is such:

1.  provide keys to nixos-anywhere with `extra-files` option
2. after the installation run `ls`/`stat` on the installation machine with ssh and note that the keys don't appear on the expected path or seemingly nowhere else

Based on some experimentation this seems to be related to a) path at which to put files doesn't exist yet b) files are directories.

For the tests to pass currently the lines:
   * "print(new_machine.succeed("spend-utxo"))" in testscript
   * and "ssh ... chown ..." in install script
  are commented out. Meaning: we don't chown the keys because the bug prevents their copying. And then we can't run the test of transaction confirmation because without the keys the node simply doesn't start.

**Comment by avnik** [comment]
`nixos-anywhere` just unmount target `/mnt` after installation. So all extra modification happens in `installer` system, not target one.  I implement setting permissions via  `tmpfiles.d` setting of systemd and it just works. https://github.com/mlabs-haskell/spo-anywhere/tree/avnik/milestone-4 This branch contain all work from #38 and contains some additional fixes.
