### ISSUE TITLE
Dummy NixOS module

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/spo-anywhere#4]
Basic NixOS module which does nothing particular, useful just for having a structure in the repository and test CI.
Do we want to keep it in [cardano.nix](https://github.com/mlabs-haskell/cardano-nix) perhaps?
While I like the idea I'm not sure if it's worth because it could be annoying having to update the `cardanoNix` input every time. What I usually do in these cases is changing the input from a github url to a local path. But still, every time we want to push something here we need to push it to `cardano.nix` before. I'm uncertain to be honest, maybe we can keep the module here for now and move it to `cardano.nix` later when it will need less frequent changes.

@avnik What do you think?

**Comment by avnik** [comment]
@aciceri you can use `--override-input`  for testing purposes.

My opinion, we should have only SPO specific code in this repo,  but also possible to develop feature here, then move to cardano.nix
